import "./globals.css";
import { Inter } from 'next/font/google'

import Topbar from "@/components/Topbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className={inter.className}>
      <body className=`min-h-full flex flex-col ${inter.className}`>
        <Topbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
