import "./globals.css";
import Topbar from "@/components/Topbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <Topbar /></Topbar>
        {children}
        </body>
    </html>
  );
}
